services:
  - type: web
    name: intellireview-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATA_GOV_API_KEY
        sync: false
      - key: DATA_GOV_RESOURCE_ID
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
    healthCheckPath: /
    autoDeploy: true
